In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [ ]:
ls

gdrive/  sample_data/

In [ ]:
cd /content/gdrive/My\ Drive/Colab Notebooks/kaggle/houseprice

/content/gdrive/My Drive/Colab Notebooks/kaggle/houseprice

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from keras.utils import to_categorical
from keras import models
from keras import layers
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import SGD
from keras.layers import Dense
from keras.utils import np_utils

Using TensorFlow backend.

In [ ]:
import pandas as pd
file1=pd.read_csv("sample_submission.csv") 

file3=pd.read_csv("test.csv", keep_default_na=False)
#file2

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,2,2008,WD,Normal,208500
1,2,20,RL,80,9600,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2007,WD,Normal,181500
2,3,60,RL,68,11250,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,9,2008,WD,Normal,223500
3,4,70,RL,60,9550,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84,14260,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,12,2008,WD,Normal,250000
5,6,50,RL,85,14115,Pave,NA,IR1,Lvl,AllPub,...,0,NA,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75,10084,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,8,2007,WD,Normal,307000
7,8,60,RL,NA,10382,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51,6120,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50,7420,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,1,2008,WD,Normal,118000
10,11,20,RL,70,11200,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,2,2008,WD,Normal,129500
11,12,60,RL,85,11924,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,7,2006,New,Partial,345000
12,13,20,RL,NA,12968,Pave,NA,IR2,Lvl,AllPub,...,0,NA,NA,NA,0,9,2008,WD,Normal,144000
13,14,20,RL,91,10652,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,8,2007,New,Partial,279500
14,15,20,RL,NA,10920,Pave,NA,IR1,Lvl,AllPub,...,0,NA,GdWo,NA,0,5,2008,WD,Normal,157000
15,16,45,RM,51,6120,Pave,NA,Reg,Lvl,AllPub,...,0,NA,GdPrv,NA,0,7,2007,WD,Normal,132000
16,17,20,RL,NA,11241,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72,10791,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66,13695,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,6,2008,WD,Normal,159000
19,20,20,RL,70,7560,Pave,NA,Reg,Lvl,AllPub,...,0,NA,MnPrv,NA,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101,14215,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,11,2006,New,Partial,325300
21,22,45,RM,57,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NA,GdPrv,NA,0,6,2007,WD,Normal,139400
22,23,20,RL,75,9742,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,9,2008,WD,Normal,230000
23,24,120,RM,44,4224,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,6,2007,WD,Normal,129900
24,25,20,RL,NA,8246,Pave,NA,IR1,Lvl,AllPub,...,0,NA,MnPrv,NA,0,5,2010,WD,Normal,154000
25,26,20,RL,110,14230,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,7,2009,WD,Normal,256300
26,27,20,RL,60,7200,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2010,WD,Normal,134800
27,28,20,RL,98,11478,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2010,WD,Normal,306000
28,29,20,RL,47,16321,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,12,2006,WD,Normal,207500
29,30,30,RM,60,6324,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60,21930,Pave,NA,IR3,Lvl,AllPub,...,0,NA,NA,NA,0,7,2006,WD,Normal,192140
1431,1432,120,RL,NA,4928,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93,10261,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80,17400,Pave,NA,Reg,Low,AllPub,...,0,NA,NA,NA,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80,8400,Pave,NA,Reg,Lvl,AllPub,...,0,NA,GdPrv,NA,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60,9000,Pave,NA,Reg,Lvl,AllPub,...,0,NA,GdWo,NA,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96,12444,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,11,2008,New,Partial,394617
1438,1439,20,RM,90,7407,Pave,NA,Reg,Lvl,AllPub,...,0,NA,MnPrv,NA,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80,11584,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79,11526,Pave,NA,IR1,Bnk,AllPub,...,0,NA,NA,NA,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NA,4426,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85,11003,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NA,8854,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63,8500,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70,8400,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NA,26142,Pave,NA,IR1,Lvl,AllPub,...,0,NA,NA,NA,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80,10000,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70,11767,Pave,NA,Reg,Lvl,AllPub,...,0,NA,GdWo,NA,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21,1533,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60,9000,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78,9262,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2009,New,Partial,287090
1452,1453,180,RM,35,3675,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90,17217,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62,7917,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85,13175,Pave,NA,Reg,Lvl,AllPub,...,0,NA,MnPrv,NA,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66,9042,Pave,NA,Reg,Lvl,AllPub,...,0,NA,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68,9717,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75,9937,Pave,NA,Reg,Lvl,AllPub,...,0,NA,NA,NA,0,6,2008,WD,Normal,147500

In [ ]:

#df=file2.drop(columns=['PassengerId','Name','Ticket','Cabin'])

d1={'WD':1,'CWD':2,'VWD':3,'New':4,'COD':5,'Con':6,'ConLw':7,'ConLI':8,'ConLD':9,'Oth':10}
d2={'Normal':1,'Abnorml':2,'AdjLand':3,'Alloca':4,'Family':5,'Partial':6}
d3={'Elev':1,'Gar2':2,'Othr':3,'Shed':4,'TenC':5,'NA':6}
d4={'GdPrv':1,'MnPrv':2,'GdWo':3,'MnWw':4,'NA':5}
d5={'Ex':1,'Gd':2,'TA':3,'Fa':4,'NA':5}
d6={'Y':1,'P':2,'N':3}
d7={'Ex':1,'Gd':2,'TA':3,'Fa':4,'Po':5,'NA':6}
d8={'Fin':1,'RFn':2,'Unf':3,'NA':4}
d9={'Attchd':1,'Basment':2,'BuiltIn':3,'CarPort':4,'Detchd':5,'NA':6,'2Types':7}
d10={'Typ':1,'Min1':2,'Min2':3 ,'Mod':4,'Maj1':5 ,'Maj2':6,'Sev':7,'Sal':8}
d11={'SBrkr':1,'FuseA':2 ,'FuseF':3 ,'FuseP':4,'Mix':5}
d12={'Y':1,'N':2}
d13={'Floor':1,'GasA':2,'GasW':3,'Grav':4,'OthW':5,'Wall':6}
d14={'GLQ':1,'ALQ':2,'BLQ':3,'Rec':4 ,'LwQ':5,'Unf':6,'NA':7}
d15={'Gd':1,'Av':2,'Mn':3,'No':4,'NA':5}
d16={'BrkTil':1,'CBlock':2 ,'PConc':3,'Slab':4,'Stone':5,'Wood':6}
d17={'BrkCmn':1,'BrkFace':2 ,'CBlock':3,'None':4,'Stone':5 }
d18={'AsbShng':1,'AsphShn':2,'BrkComm':3,'BrkFace':4,'CBlock':5 ,'CemntBd':6,'HdBoard':7 ,'ImStucc':8 ,'MetalSd':9,'Other':10 ,'Plywood':11,'PreCast':12,'Stone':13,'Stucco':14 ,'VinylSd':15,'Wd Sdng':16,'WdShing':17}
d19={ 'ClyTile':1 ,'CompShg':2, ,'Membran':3,'Metal':4,'Roll':5,'Tar&Grv':6,'WdShake':7 ,'WdShngl':8 }
d20={  'Flat':1,'Gable':2 ,'Gambrel':3 ,'Hip':4 ,'Mansard':5,'Shed':6 }
d21={ '1Story':1 ,'1.5Fin':2  ,'1.5Unf':3,'2Story':4 ,'2.5Fin':5 ,'2.5Unf':6 ,'SFoyer':7,'SLvl':8}



#print(d1)
file2=pd.read_csv("train.csv", keep_default_na=False)
file2.dtypes
file2['SaleType'].replace(d1, inplace=True)
file2['SaleCondition'].replace(d2, inplace=True)
file2['MiscFeature'].replace(d3, inplace=True)
file2['Fence'].replace(d4, inplace=True)
file2['PoolQC'].replace(d5, inplace=True)
file2['PavedDrive'].replace(d6, inplace=True)
file2['GarageCond'].replace(d7, inplace=True)
file2['GarageQual'].replace(d7, inplace=True)
file2['GarageFinish'].replace(d8, inplace=True)
file2['GarageType'].replace(d9, inplace=True)
file2['FireplaceQu'].replace(d7, inplace=True)
file2['Functional'].replace(d10, inplace=True)

file2['KitchenQual'].replace(d7, inplace=True)
file2['Electrical'].replace(d11, inplace=True)
file2['CentralAir'].replace(d12, inplace=True)
file2['HeatingQC'].replace(d7, inplace=True)

file2['BsmtFinType2'].replace(d14, inplace=True)
file2['Heating'].replace(d13, inplace=True)
file2['BsmtFinType1'].replace(d14, inplace=True)
file2['BsmtExposure'].replace(d15, inplace=True)
file2['BsmtCond'].replace(d7, inplace=True)
file2['BsmtQual'].replace(d7, inplace=True)
file2['Foundation'].replace(d16, inplace=True)
file2['ExterCond'].replace(d7, inplace=True)

file2['ExterQual'].replace(d7, inplace=True)
file2['MasVnrType'].replace(d17, inplace=True)
file2['Exterior2nd'].replace(d18, inplace=True)
file2['Exterior1st'].replace(d18, inplace=True)
file2['RoofMatl'].replace(d19, inplace=True)


file2['RoofStyle'].replace(d20, inplace=True)
file2['HouseStyle'].replace(d21, inplace=True)
file2['Exterior2nd'].replace(d18, inplace=True)
file2['Exterior1st'].replace(d18, inplace=True)
file2['RoofMatl'].replace(d19, inplace=True)



(file2)


#X=df.values

#y=y.values


#y


#df.replace

#df.values
#df = pd.DataFrame(file1, columns=['Survived'])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65,8450,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,2,2008,1,1,208500
1,2,20,RL,80,9600,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2007,1,1,181500
2,3,60,RL,68,11250,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,9,2008,1,1,223500
3,4,70,RL,60,9550,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,2,2006,1,2,140000
4,5,60,RL,84,14260,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,12,2008,1,1,250000
5,6,50,RL,85,14115,Pave,NA,IR1,Lvl,AllPub,...,0,5,2,4,700,10,2009,1,1,143000
6,7,20,RL,75,10084,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,8,2007,1,1,307000
7,8,60,RL,NA,10382,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,4,350,11,2009,1,1,200000
8,9,50,RM,51,6120,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,4,2008,1,2,129900
9,10,190,RL,50,7420,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,1,2008,1,1,118000
10,11,20,RL,70,11200,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,2,2008,1,1,129500
11,12,60,RL,85,11924,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,7,2006,4,6,345000
12,13,20,RL,NA,12968,Pave,NA,IR2,Lvl,AllPub,...,0,5,5,6,0,9,2008,1,1,144000
13,14,20,RL,91,10652,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,8,2007,4,6,279500
14,15,20,RL,NA,10920,Pave,NA,IR1,Lvl,AllPub,...,0,5,3,6,0,5,2008,1,1,157000
15,16,45,RM,51,6120,Pave,NA,Reg,Lvl,AllPub,...,0,5,1,6,0,7,2007,1,1,132000
16,17,20,RL,NA,11241,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,4,700,3,2010,1,1,149000
17,18,90,RL,72,10791,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,4,500,10,2006,1,1,90000
18,19,20,RL,66,13695,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,6,2008,1,1,159000
19,20,20,RL,70,7560,Pave,NA,Reg,Lvl,AllPub,...,0,5,2,6,0,5,2009,5,2,139000
20,21,60,RL,101,14215,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,11,2006,4,6,325300
21,22,45,RM,57,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,5,1,6,0,6,2007,1,1,139400
22,23,20,RL,75,9742,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,9,2008,1,1,230000
23,24,120,RM,44,4224,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,6,2007,1,1,129900
24,25,20,RL,NA,8246,Pave,NA,IR1,Lvl,AllPub,...,0,5,2,6,0,5,2010,1,1,154000
25,26,20,RL,110,14230,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,7,2009,1,1,256300
26,27,20,RL,60,7200,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2010,1,1,134800
27,28,20,RL,98,11478,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2010,1,1,306000
28,29,20,RL,47,16321,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,12,2006,1,1,207500
29,30,30,RM,60,6324,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,5,2008,1,1,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60,21930,Pave,NA,IR3,Lvl,AllPub,...,0,5,5,6,0,7,2006,1,1,192140
1431,1432,120,RL,NA,4928,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,10,2009,1,1,143750
1432,1433,30,RL,60,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,5,5,6,0,8,2007,1,1,64500
1433,1434,60,RL,93,10261,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,5,2008,1,1,186500
1434,1435,20,RL,80,17400,Pave,NA,Reg,Low,AllPub,...,0,5,5,6,0,5,2006,1,1,160000
1435,1436,20,RL,80,8400,Pave,NA,Reg,Lvl,AllPub,...,0,5,1,6,0,7,2008,5,2,174000
1436,1437,20,RL,60,9000,Pave,NA,Reg,Lvl,AllPub,...,0,5,3,6,0,5,2007,1,1,120500
1437,1438,20,RL,96,12444,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,11,2008,4,6,394617
1438,1439,20,RM,90,7407,Pave,NA,Reg,Lvl,AllPub,...,0,5,2,6,0,4,2010,1,1,149700
1439,1440,60,RL,80,11584,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,11,2007,1,1,197000
1440,1441,70,RL,79,11526,Pave,NA,IR1,Bnk,AllPub,...,0,5,5,6,0,9,2008,1,1,191000
1441,1442,120,RM,NA,4426,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2008,1,1,149300
1442,1443,60,FV,85,11003,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,4,2009,1,1,310000
1443,1444,30,RL,NA,8854,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2009,1,1,121000
1444,1445,20,RL,63,8500,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,11,2007,1,1,179600
1445,1446,85,RL,70,8400,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2007,1,1,129000
1446,1447,20,RL,NA,26142,Pave,NA,IR1,Lvl,AllPub,...,0,5,5,6,0,4,2010,1,1,157900
1447,1448,60,RL,80,10000,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,12,2007,1,1,240000
1448,1449,50,RL,70,11767,Pave,NA,Reg,Lvl,AllPub,...,0,5,3,6,0,5,2007,1,1,112000
1449,1450,180,RM,21,1533,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,8,2006,1,2,92000
1450,1451,90,RL,60,9000,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,9,2009,1,1,136000
1451,1452,20,RL,78,9262,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2009,4,6,287090
1452,1453,180,RM,35,3675,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,5,2006,1,1,145000
1453,1454,20,RL,90,17217,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,7,2006,1,2,84500
1454,1455,20,FV,62,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,5,5,6,0,10,2009,1,1,185000
1455,1456,60,RL,62,7917,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,8,2007,1,1,175000
1456,1457,20,RL,85,13175,Pave,NA,Reg,Lvl,AllPub,...,0,5,2,6,0,2,2010,1,1,210000
1457,1458,70,RL,66,9042,Pave,NA,Reg,Lvl,AllPub,...,0,5,1,4,2500,5,2010,1,1,266500
1458,1459,20,RL,68,9717,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,4,2010,1,1,142125
1459,1460,20,RL,75,9937,Pave,NA,Reg,Lvl,AllPub,...,0,5,5,6,0,6,2008,1,1,147500

In [ ]:
df=file3.drop(columns=['Name','Ticket','Cabin'])
df=df.fillna(df['Age'].mean())
df=df.replace('male',1)
df=df.replace('female',2)
df=df.replace('S',1)
df=df.replace('C',2)
df=df.replace('Q',2)
y_id=df['PassengerId']
df=df.drop(columns=['PassengerId'])
X_test=df.values
X_test
df=file1[:891]
print(df)

y_act=df['Survived']
y_act=y_act.values

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
print(X.shape)
print(y.shape)
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X, y)  
#x_test[0]
predicted=clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_act, predicted)

(891, 7)
(891,)

0.6794258373205742

In [ ]:
from sklearn import naive_bayes
classifier = naive_bayes.GaussianNB()
model = classifier.fit(X,y)
prediction = model.predict(X_test)
accuracy_score(y_act, prediction)

0.8301435406698564

In [ ]:
import xgboost as xgb
clf = xgb.XGBClassifier(objective="binary:logistic", random_state=42)
clf = clf.fit(X, y)
prediction__ = clf.predict(X_test)
app=prediction__.tolist()
df1 = pd.DataFrame({'Survived':app})
#print(df1)
df__=df['PassengerId']
df__=df__.values
df__=df__.tolist()
#print(df__)
df2 = pd.DataFrame({'PassengerId':df__})
df_ = pd.concat([df2, df1],axis=1)
export_csv=df_.to_csv('file1.csv',index=False)
print(df_)
accuracy_score(y_act, prediction__)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         0
19           911         0
20           912         0
21           913         1
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         1
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

0.8875598086124402

In [ ]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(16,4), random_state=1)
clf.fit(X, y)
prediction_ = clf.predict(X_test)
app=prediction_.tolist()
df1 = pd.DataFrame({'Survived':app})
#print(df1)
df__=df['PassengerId']
df__=df__.values
df__=df__.tolist()
#print(df__)
df2 = pd.DataFrame({'PassengerId':df__})
df_ = pd.concat([df2, df1],axis=1)
df_.to_csv('file3.csv',index=False)
#print(df_)

accuracy_score(y_act, prediction_)

0.6363636363636364

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=65, max_depth=3,random_state=0)
#print(y.shape)
clf.fit(X, y)
prediction_ = clf.predict(X_test)
app=prediction_.tolist()
df1 = pd.DataFrame({'Survived':app})
#print(df1)
df__=df['PassengerId']
df__=df__.values
df__=df__.tolist()
#print(df__)
df2 = pd.DataFrame({'PassengerId':df__})
df_ = pd.concat([df2, df1],axis=1)
df_.to_csv('file.csv',index=False)
#print(df_)

accuracy_score(y_act, prediction_)

0.9234449760765551